const emailData: any = [
    {
        "mid": "209834578",
        "year": "2022",
        "month": "3",
        "day": "12",
        "hour": "3",
        "minute": "3",
        "day_since_hire": "235",
        "sender": "Lexie Stone",
        "rcpt": "Lucie Wason",
        "rcpt_count": "10",
        "size": "9087",
        "files": "sunlife internal",
        "files_sensitive_count": "1",
        "subject": "urgent",
        "lev_mail": "1",
        "file_count": "29",
        "division": "sunlife",
        "employee_status ": "active"
    },
    {
        "mid": "209834579",
        "year": "2022",
        "month": "4",
        "day": "13",
        "hour": "3",
        "minute": "3",
        "day_since_hire": "345",
        "sender": "Louis He",
        "rcpt": "Ellie Chew",
        "rcpt_count": "2",
        "size": "9087",
        "files": "business schedule",
        "files_sensitive_count": "246",
        "subject": "urgent",
        "lev_mail": "1",
        "file_count": "2",
        "division": "sunlife",
        "employee_status ": "active"
    },
    {
        "mid": "209834580",
        "year": "2022",
        "month": "5",
        "day": "14",
        "hour": "3",
        "minute": "3",
        "day_since_hire": "2745",
        "sender": "Haley Fungus",
        "rcpt": "Oscar Orando",
        "rcpt_count": "3",
        "size": "9087",
        "files": "random picture",
        "files_sensitive_count": "10",
        "subject": "urgent",
        "lev_mail": "1",
        "file_count": "2",
        "division": "sunlife",
        "employee_status ": "active"
    },
    {
        "mid": "209834581",
        "year": "2022",
        "month": "5",
        "day": "15",
        "hour": "3",
        "minute": "3",
        "day_since_hire": "234",
        "sender": "Larry Newson",
        "rcpt": "Shirley Harry",
        "rcpt_count": "5",
        "size": "9087",
        "files": "important notice",
        "files_sensitive_count": "71",
        "subject": "urgent",
        "lev_mail": "1",
        "file_count": "2",
        "division": "sunlife",
        "employee_status ": "active"
    },
    {
        "mid": "209834582",
        "year": "2022",
        "month": "5",
        "day": "16",
        "hour": "3",
        "minute": "3",
        "day_since_hire": "1234",
        "sender": "Sharon Kelly",
        "rcpt": "Jackson Abori",
        "rcpt_count": "8",
        "size": "9087",
        "files": "important notice",
        "files_sensitive_count": "19",
        "subject": "urgent",
        "lev_mail": "1",
        "file_count": "2",
        "division": "sunlife",
        "employee_status ": "active"
    },
    {
        "mid": "209834583",
        "year": "2022",
        "month": "5",
        "day": "17",
        "hour": "3",
        "minute": "3",
        "day_since_hire": "2345",
        "sender": "Stacy Dabiri",
        "rcpt": "Tony Johnson",
        "rcpt_count": "5",
        "size": "9087",
        "files": "business document",
        "files_sensitive_count": "22",
        "subject": "urgent",
        "lev_mail": "1",
        "file_count": "2",
        "division": "sunlife",
        "employee_status ": "active"
    },
    {
        "mid": "209834584",
        "year": "2022",
        "month": "5",
        "day": "18",
        "hour": "3",
        "minute": "3",
        "day_since_hire": "747",
        "sender": "Tuntun Nie",
        "rcpt": "Blanc Jeans",
        "rcpt_count": "10",
        "size": "9087",
        "files": "important notice",
        "files_sensitive_count": "300",
        "subject": "urgent",
        "lev_mail": "1",
        "file_count": "2",
        "division": "sunlife",
        "employee_status ": "active"
    },
    {
        "mid": "209834585",
        "year": "2022",
        "month": "5",
        "day": "19",
        "hour": "3",
        "minute": "3",
        "day_since_hire": "76",
        "sender": "Keivan Abiri",
        "rcpt": "Reem Simpson",
        "rcpt_count": "3",
        "size": "9087",
        "files": "quick notice",
        "files_sensitive_count": "256",
        "subject": "urgent",
        "lev_mail": "1",
        "file_count": "2",
        "division": "sunlife",
        "employee_status ": "active"
    },
    {
        "mid": "209834586",
        "year": "2022",
        "month": "5",
        "day": "20",
        "hour": "3",
        "minute": "3",
        "day_since_hire": "247",
        "sender": "Kylie Han",
        "rcpt": "Elvis Louis",
        "rcpt_count": "3",
        "size": "97",
        "files": "random files",
        "files_sensitive_count": "48",
        "subject": "urgent",
        "lev_mail": "1",
        "file_count": "2",
        "division": "sunlife",
        "employee_status ": "active"
    },
    {
        "mid": "209834586",
        "year": "2022",
        "month": "5",
        "day": "20",
        "hour": "3",
        "minute": "3",
        "day_since_hire": "247",
        "sender": "Kylie White",
        "rcpt": "Elvis Brank",
        "rcpt_count": "4",
        "size": "9870",
        "files": "random files",
        "files_sensitive_count": "6",
        "subject": "urgent",
        "lev_mail": "1",
        "file_count": "2",
        "division": "sunlife",
        "employee_status ": "active"
    },
    {
        "mid": "209834587",
        "year": "2022",
        "month": "5",
        "day": "20",
        "hour": "3",
        "minute": "3",
        "day_since_hire": "247",
        "sender": "Kylie Bruenello",
        "rcpt": "Elvis Arnika",
        "rcpt_count": "19",
        "size": "19087",
        "files": "random files",
        "files_sensitive_count": "21",
        "subject": "urgent",
        "lev_mail": "1",
        "file_count": "2",
        "division": "sunlife",
        "employee_status ": "active"
    }
]

export default emailData